### ISSUE TITLE
Issue trying to use in Package

### ISSUE THREAD

**Issue by k-jay-c** [digital-loukoum/grubber#1]
Trying to use this in a VSCode Extension and have installed the library using npm.  I get the following error, any advice on how I can use this in my project?

https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample is the sample project I'm using.

Any help you can provide would be greatly appreciated.

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: node_modules/@digitak/grubber/library/index.js
require() of ES modules is not supported.
require() of node_modules/@digitak/grubber/library/index.js from tempCodeRunnerFile.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" 
```

**Comment by Gin-Quin** [comment]
As the error explains it, Grubber is an esm module, not a commonJS, so you must use:

```ts
import { grub } from "@digitak/grubber";
```

rather than:

```ts
const { grub } = require("@digitak/grubber");
```
 
which will not work.

If you are using Node, you need to set `"type": "module"` in your package.json to start using modules.
