### ISSUE TITLE
patchJsImports utility treats in-workspace packages as local imports

### ISSUE THREAD

**Issue by spautz** [digital-loukoum/grubber#5]
We have a pnpm workspace with several packages. When one package imports another which happens to come from the workspace, `patchJsImports` interprets it as a relative import. The result is that, during build, the import gets transformed from a module name into a local path, which then fails when the package is published.

### Example
Suppose a monorepo holds `@company/package-one` and `@company/package-two`. Package-one has a dependency on package-two:
```
// package-one/src/index.ts
import { stuff } from '@company/package-two';
```

This import should be left as-is during the build, because `@company/package-two` is a normal package, not a relative import -- it just happens to be resolved from the workspace. Instead, however, it gets transformed to the resolved path:
```
// package-one/dist/index.js
import { stuff } from '../../package-two/dist/index.js';
```
So when package-one gets published, the import fails and nobody can use the package.

### What's happening
1. The `"@company/package-two"` import target gets resolved into a path like `"/path/to/repo/package-two/dist/index.js"` ([patchJsImports.ts:49](https://github.com/digital-loukoum/grubber/blob/be49be0a8096b7f08485738becefb8ae31ef74e5/source/utilities/patchJsImports.ts#L49))
2. This path gets tested against `NODE_MODULES_DIR_REGEX` ([patchJsImports.ts:52](https://github.com/digital-loukoum/grubber/blob/be49be0a8096b7f08485738becefb8ae31ef74e5/source/utilities/patchJsImports.ts#L52)), which specifically looks for "node_modules" in the path ([patchJsImports.ts:18](https://github.com/digital-loukoum/grubber/blob/be49be0a8096b7f08485738becefb8ae31ef74e5/source/utilities/patchJsImports.ts#L18))
3. Because the regex test fails, it gets converted to a relative path, and the transformed path is used instead of the original module name.

### Some possible solutions

A) Explicitly check for relative paths and aliases, and only resolve those, instead of resolving all imports. It looks like this would be as simple as combining [resolveAliases](https://github.com/digital-loukoum/grubber/blob/be49be0a8096b7f08485738becefb8ae31ef74e5/source/utilities/resolveAliases.ts) with the relative-path check ([patchJsImports.ts:56](https://github.com/digital-loukoum/grubber/blob/be49be0a8096b7f08485738becefb8ae31ef74e5/source/utilities/patchJsImports.ts#L56))

B) If the resolved file is outside of the `directories` passed in, do not transform its import. This could be combined with the `isNodeModulePath` check, so that any out-of-directory file is treated as an external module

I'd be happy to submit a PR, if one of these sounds reasonable

**Comment by Gin-Quin** [comment]
I think the correct way to do it is to indicate to `patchJsImports` what should be considered as external and should not be touched.

You can actually already do it by providing an alias that resolves to `null` (`null` meaning "leave this dependency untouched"):

```ts
patchJsImports(directories, [
  {
    find: /^[a-z@\/].*$/i, // all non-relative paths...
    replacement: null, // ... are left as-is
 },
] 
```

It is debatable, but I don't think it should be the default behavior. You might want to resolve non-relative paths.

Same for **B)**, you might want to transform external modules.

I would advise using the `aliases` property to get what you need.
